// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFSws19y8ccS-9OuXMAZXvfWfTlTz629Q',
    appId: '1:383280628738:web:0c69c396a3f7d644f9d31b',
    messagingSenderId: '383280628738',
    projectId: 'sondage-3c953',
    authDomain: 'sondage-3c953.firebaseapp.com',
    storageBucket: 'sondage-3c953.firebasestorage.app',
    measurementId: 'G-MBSE8XX4D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBWfHheaCVnOaXtYsPW8wbRAIUaNAXb3M',
    appId: '1:383280628738:android:02e7edccb3a4a0b2f9d31b',
    messagingSenderId: '383280628738',
    projectId: 'sondage-3c953',
    storageBucket: 'sondage-3c953.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr8q80T0hah-MxWelgW3PIUsKz-Dk1UvM',
    appId: '1:383280628738:ios:75fd0e17be2bd452f9d31b',
    messagingSenderId: '383280628738',
    projectId: 'sondage-3c953',
    storageBucket: 'sondage-3c953.firebasestorage.app',
    iosBundleId: 'com.example.sondage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr8q80T0hah-MxWelgW3PIUsKz-Dk1UvM',
    appId: '1:383280628738:ios:75fd0e17be2bd452f9d31b',
    messagingSenderId: '383280628738',
    projectId: 'sondage-3c953',
    storageBucket: 'sondage-3c953.firebasestorage.app',
    iosBundleId: 'com.example.sondage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFSws19y8ccS-9OuXMAZXvfWfTlTz629Q',
    appId: '1:383280628738:web:1527aeac350ab2b8f9d31b',
    messagingSenderId: '383280628738',
    projectId: 'sondage-3c953',
    authDomain: 'sondage-3c953.firebaseapp.com',
    storageBucket: 'sondage-3c953.firebasestorage.app',
    measurementId: 'G-GF1EK8DV0Y',
  );
}
